theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  posts:
    list:
      show_categories: true
  logo:
      header: "/assets/images/logo.png"
      footer: "/assets/images/logo-footer.png"

  image_sizes:
    design_system:
      hero:
        desktop:  1920
    sections:
      categories:
        hero_term:
          desktop:  1920
      home:
        hero:
          desktop:  1920
      pages:
        hero:
          desktop:  1920