baseURL: https://mit-africanfutures.netlify.app/
theme: osuny-hugo-theme

## LANGUAGE
defaultContentLanguage: en
languageCode: en

## ADVANCED
paginate: 18
permalinks:
  posts:          /news/:year/:month/:day/:slug/
  categories:     /news/:slug/
taxonomies:
  author:         authors
  category:       categories
