# baseURL: https://mit-africanfutures.netlify.app/
baseURL: https://www.google.com/
theme: osuny-hugo-theme

## LANGUAGE
defaultContentLanguage: en
languageCode: en

## ADVANCED
paginate: 18
enableRobotsTXT: true
