theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  posts:
    index:
      show_categories: false
      truncate_description: 200 # Set to 0 to disable truncate
      layout: grid
    list:
      show_categories: true
  search: 
    active: true
    position: footer
    appearance: both
  breadcrumb:
    position: after-hero
  summary:
    position: content
  image_sizes:
    design_system:
      hero:
        desktop:  1920
    sections:
      categories:
        hero_term:
          desktop:  1920
      home:
        hero:
          desktop:  1920
      pages:
        hero:
          desktop:  1920
