params:
  cdnkey: https://osuny-1b4da.kxcdn.com
  cookie_banner:
    enable: false
    blank: true
    page: https://gdpr.eu/cookies/
baseURL: https://mit-africanfutures.netlify.app/
defaultContentLanguage: fr
languageCode: fr
languages:
  fr:
    title: African futures
theme: osuny-hugo-theme
paginate: 18
permalinks:
  posts:          /actualites/:year/:month/:day/:slug/
  categories:     /actualites/:slug/
taxonomies:
  author:         authors
  category:       categories
